<a href="https://colab.research.google.com/github/iamsonia9/Web_scrap/blob/main/KNN_Assignment13(Sonia).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [130]:
!pip install mlxtend

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [131]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from mlxtend.plotting import plot_decision_regions
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split


**Importing the dataset**

In [132]:
df = pd.read_csv("/content/Social_Network_Ads (1).csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [133]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [134]:
X = df[["Age","EstimatedSalary"]]
X

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [135]:
y = df[["Purchased"]]

**Splitting the dataset into the Training set and Test set**

In [136]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

**Feature Scaling**

In [137]:
from sklearn.preprocessing import StandardScaler

In [138]:
sc_x = StandardScaler()

In [139]:
X_train = sc_x.fit_transform(X_train)

In [140]:
X_test = sc_x.transform(X_test)

In [141]:
X_train

array([[ 1.02640698, -0.82883197],
       [-0.90305898,  0.53030684],
       [ 0.1581473 ,  0.28319069],
       [-1.28895218, -0.39637871],
       [-0.32421919, -1.32306426],
       [ 2.18408656,  1.05542865],
       [ 1.70172007,  1.76588757],
       [ 1.79819337,  1.11720769],
       [-0.1312726 ,  2.35278842],
       [-1.09600558, -1.57018041],
       [-0.22774589,  0.1287431 ],
       [-0.90305898, -0.39637871],
       [-0.22774589,  0.22141165],
       [-0.22774589,  2.44545698],
       [-1.09600558, -0.48904727],
       [-0.71011239,  0.65386491],
       [ 1.60524677, -1.29217475],
       [-0.0347993 ,  2.13656179],
       [-1.38542547, -0.05659401],
       [ 0.54404049,  2.01300372],
       [ 1.12288028, -0.98327956],
       [-0.1312726 , -1.07594812],
       [ 0.3510939 ,  0.1287431 ],
       [ 1.12288028, -0.08748353],
       [ 1.31582688, -1.3848433 ],
       [-1.09600558, -1.10683764],
       [ 0.1581473 ,  1.17898672],
       [ 0.1581473 , -0.79794245],
       [ 0.54404049,

In [142]:
X_test

array([[ 0.44756719, -0.42726823],
       [ 0.3510939 ,  0.37585925],
       [-0.22774589, -1.41573282],
       [ 1.31582688,  2.41456746],
       [-0.0347993 ,  0.31408021],
       [ 0.44756719, -0.08748353],
       [-1.77131867, -1.32306426],
       [-0.42069249, -0.24193112],
       [-1.48189877,  0.40674877],
       [ 1.21935358, -0.73616341],
       [-0.80658568,  0.4685278 ],
       [ 0.92993369, -1.0450586 ],
       [ 0.73698709,  1.95122468],
       [ 0.92993369,  2.35278842],
       [-0.1312726 , -0.42726823],
       [-1.38542547, -1.47751186],
       [-1.57837207, -1.60106993],
       [-1.38542547,  0.43763828],
       [-0.99953228,  0.68475443],
       [-1.48189877, -1.53929089],
       [ 1.79819337, -0.24193112],
       [-0.22774589,  0.15963262],
       [ 1.02640698, -1.16861667],
       [-0.22774589,  0.1287431 ],
       [-0.80658568,  0.4685278 ],
       [ 0.3510939 ,  0.1287431 ],
       [ 0.3510939 , -0.48904727],
       [ 1.89466667, -1.29217475],
       [ 2.18408656,

In [143]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

**Fitting K-NN to the Training set**

In [144]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(3)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

/usr/local/lib/python3.8/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


0.9083333333333333

**Predicting the Test set results**

In [149]:
from sklearn.metrics import roc_auc_score

for i in [1,2,3,4,5,6,7,8,9,10,20,50]:
  knn = KNeighborsClassifier(i) #initialising the model
  knn.fit(X_train,y_train) # training the model
  print("K value  : " , i, " train score : ", knn.score(X_train,y_train) , " cv score : ", np.mean(cross_val_score(knn, X_train, y_train, cv=10))) #predicting using the model


knn = KNeighborsClassifier(5)
knn.fit(X_train,y_train)
knn.score(X_test,y_test)

K value  :  1  train score :  1.0  cv score :  0.8571428571428571
K value  :  2  train score :  0.9285714285714286  cv score :  0.8714285714285716
K value  :  3  train score :  0.9321428571428572  cv score :  0.9071428571428571
K value  :  4  train score :  0.9285714285714286  cv score :  0.8964285714285714
K value  :  5  train score :  0.925  cv score :  0.9
K value  :  6  train score :  0.9178571428571428  cv score :  0.8964285714285716
K value  :  7  train score :  0.9285714285714286  cv score :  0.9142857142857143
K value  :  8  train score :  0.925  cv score :  0.9071428571428571
K value  :  9  train score :  0.9285714285714286  cv score :  0.9142857142857143
K value  :  10  train score :  0.9142857142857143  cv score :  0.9071428571428571
K value  :  20  train score :  0.9214285714285714  cv score :  0.9071428571428571
K value  :  50  train score :  0.8928571428571429  cv score :  0.8785714285714284


0.875

In [146]:
y_pred = knn.predict(X_test)

y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1])

**Making the Confusion Matrix**

In [147]:
from sklearn.metrics import accuracy_score, plot_roc_curve, roc_curve,roc_auc_score,confusion_matrix, f1_score

In [148]:
confusion_matrix(y_test,y_pred)

array([[72,  7],
       [ 8, 33]])